spring.application.name=stockservice
spring.config.import=optional:configtree:/run/secrets/
server.port=8082
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
app.allowed-users=admin,mockUser