spring.application.name=server
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/gazprom
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update